# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# About: actions/checkout@v2: Why needed for running code (makefile or not): https://stackoverflow.com/questions/66918575/how-to-use-your-own-makefile-in-github-actions
name: Build and release

on:
  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
    - cron: "0 0 1 * *"  # monthly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Create .env file
      run: |
        echo -en "API_KEY=${{ secrets.API_KEY }}" > .env
    - name: Build
      run: |
        make build
# This one wouldn't work unless it was a tag and on-push.
#      uses: softprops/action-gh-release@v1
#    - name: Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
# Apparently, GITHUB_TOKEN is auto-created: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
# ...even though I don't see it here: https://github.com/monarch-initiative/omim/settings/secrets/actions
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
#        title: "My Title"
        prerelease: false
        files: |
          omim.ttl
