# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# About: actions/checkout@v2: Why needed for running code (makefile or not): https://stackoverflow.com/questions/66918575/how-to-use-your-own-makefile-in-github-actions
name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Create .env file
      run: |
        echo -en "API_KEY=${{ secrets.API_KEY }}" > .env
    - name: Build
      run: |
        make all
